# Generated by Django 5.1.2 on 2024-10-21 20:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_operator', models.CharField(max_length=50)),
                ('event_operation', models.CharField(choices=[('seed', 'Seeding'), ('fertilize', 'Fertilizing'), ('irrigate', 'Irrigating'), ('harvest', 'Harvesting'), ('till', 'Tilling'), ('spray', 'Spraying'), ('other', 'Other')], max_length=10)),
                ('event_location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_type', models.CharField(max_length=50)),
                ('fertilizer_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='powerunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerunit_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_planted', models.CharField(max_length=50)),
                ('seed_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('note', models.TextField()),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrelog.fertilizer')),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrelog.event')),
                ('powerunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrelog.powerunit')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrelog.seed')),
            ],
        ),
    ]
