# Generated by Django 5.1.2 on 2024-10-22 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acrelog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_types",
                    models.CharField(
                        choices=[
                            ("spray", "Spread/Spray"),
                            ("tillage", "Tillage"),
                            ("plant", "Plant"),
                            ("harvest", "Harvest"),
                            ("soil_sampling", "Soil Sampled"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="spray",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("powerunit_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name="powerunit",
            new_name="location",
        ),
        migrations.RemoveField(
            model_name="log",
            name="log_id",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="powerunit_type",
            new_name="location_name",
        ),
        migrations.RemoveField(
            model_name="log",
            name="powerunit",
        ),
        migrations.AddField(
            model_name="fertilizer",
            name="powerunit_type",
            field=models.CharField(default="-", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seed",
            name="powerunit_type",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="log",
            name="operation",
            field=models.ForeignKey(
                default="0",
                on_delete=django.db.models.deletion.CASCADE,
                to="acrelog.operation",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="event",
        ),
    ]
