# Generated by Django 5.1.2 on 2024-10-22 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acrelog", "0002_operation_operator_spray_rename_powerunit_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="event_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
