# Generated by Django 5.1.2 on 2024-10-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acrelog", "0003_operation_event_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operation",
            old_name="event_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="operation",
            old_name="event_types",
            new_name="operation",
        ),
    ]
