# Generated by Django 5.1.2 on 2024-10-22 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acrelog", "0004_rename_event_date_operation_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operation",
            old_name="operation",
            new_name="event",
        ),
    ]
