# Generated by Django 5.1.2 on 2024-10-22 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acrelog", "0005_rename_operation_operation_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("spray", "Spread/Spray"),
                            ("tillage", "Tillage"),
                            ("plant", "Plant"),
                            ("harvest", "Harvest"),
                            ("soil_sampling", "Soil Sampled"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="operation",
            name="date",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="event",
        ),
        migrations.AddField(
            model_name="operation",
            name="operation",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
