# Generated by Django 5.1.2 on 2024-10-22 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acrelog", "0008_remove_event_id_event_primary_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="primary_key",
            new_name="event_id",
        ),
    ]
