# Generated by Django 5.1.2 on 2024-10-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acrelog", "0010_remove_event_event_id_event_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fertilizer",
            name="powerunit_type",
        ),
        migrations.RemoveField(
            model_name="seed",
            name="powerunit_type",
        ),
    ]
